require("pedros.core.options")
require("pedros.core.keymaps")
require("pedros.launch")
require("pedros.autocmds")

spec("pedros.colorscheme")
spec("pedros.telescope")
spec("pedros.nvim-tree")
spec("pedros.comment")
spec("pedros.treesitter")
spec("pedros.lualine")
spec("pedros.gitsigns")
-- spec("pedros.bufferline")
spec("pedros.copilot")
spec("pedros.noice")
spec("pedros.surround")
spec("pedros.lazygit")
spec("pedros.markdown-preview")
spec("pedros.illuminate")
spec("pedros.null-ls")
spec("pedros.mason")
spec("pedros.lsp")
spec("pedros.cmp")
spec("pedros.presence")
spec("pedros.schema-store")
spec("pedros.which-key")
spec("pedros.dropbar")
spec("pedros.indentline")
spec("pedros.diffview")
spec("pedros.harpoon")
spec("pedros.tabby")
spec("pedros.bqf")
spec("pedros.project")
spec("pedros.ufo")
-- spec("pedros.alpha")

spec("pedros.tmux-navigator")

require("pedros.lazy")
